listen: "127.0.0.1:8053"
forwarder: ""
enable_dnssec: false
api_token: "devtoken"
rest_listen: "127.0.0.1:18080"
auto_soa_on_missing: true
default_ttl: 300

db:
  driver: "sqlite"
  dsn: "file:smaillgeodns_dev.db?_foreign_keys=on"

geoip:
  enabled: true
  mmdb_path: "./geoipdb"
  reload_sec: 300
  use_ecs: true

update:
  enabled: true
  require_tsig: false
  tsig_secrets: {}

log:
  dns_verbose: true

performance:
  cache_size: 1024
  dns_timeout_sec: 2
  forwarder_timeout_sec: 2
