listen: "127.0.0.1:8053"
forwarder: ""
enable_dnssec: false
api_token: "devtoken"
rest_listen: "127.0.0.1:18080"
auto_soa_on_missing: true
default_ttl: 300

db:
  driver: "sqlite"
  dsn: "file:namedot_dev.db?_foreign_keys=on"

geoip:
  enabled: true
  mmdb_path: "./geoipdb"
  reload_sec: 300
  use_ecs: true
  # download_urls:
  #   - "https://example.com/GeoLite2-Country.mmdb"
  #   - "https://example.com/GeoLite2-ASN.mmdb"
  # download_interval_sec: 86400  # 24 hours

log:
  dns_verbose: true

performance:
  cache_size: 1024
  dns_timeout_sec: 2
  forwarder_timeout_sec: 2

admin:
  enabled: true
  username: admin
  password_hash: "$2a$10$0WB2kBhwpbU9.nmxVD2qs.4.1cz9vxrI8Vd58X7arA1rzp57B5zfW"
