listen: "0.0.0.0:53"
forwarder: ""
enable_dnssec: false
# api_token: "change-me-in-production"  # Deprecated: use api_token_hash instead
api_token_hash: ""  # Generate with: ./namedot --gen-token yourToken
rest_listen: "0.0.0.0:8080"
# tls_cert_file: "/path/to/cert.pem"  # Path to TLS certificate for HTTPS
# tls_key_file: "/path/to/key.pem"    # Path to TLS private key for HTTPS
# tls_reload_sec: 3600                # Reload certificate every N seconds (default: 3600)
# allowed_cidrs:                      # Restrict REST API access to specific IP ranges (empty = allow all)
#   - "127.0.0.0/8"                   # Localhost
#   - "10.0.0.0/8"                    # Private network
#   - "192.168.1.0/24"                # Local subnet
#   - "2001:db8::/32"                 # IPv6 network
auto_soa_on_missing: true
default_ttl: 300

db:
  driver: "postgres"
  dsn: "host=postgres port=5432 user=geodns password=geodns_secret dbname=geodns sslmode=disable"

geoip:
  enabled: true
  mmdb_path: "./geoipdb"
  reload_sec: 300
  use_ecs: true
  # download_urls:
  #   - "https://example.com/GeoLite2-Country.mmdb"
  #   - "https://example.com/GeoLite2-ASN.mmdb"
  # download_interval_sec: 86400  # 24 hours

log:
  dns_verbose: true
  sql_debug: false

performance:
  cache_size: 2048
  dns_timeout_sec: 5
  forwarder_timeout_sec: 3
