listen: "0.0.0.0:53"
forwarder: ""
enable_dnssec: false
api_token: "change-me-in-production"
rest_listen: "0.0.0.0:8080"
auto_soa_on_missing: true
default_ttl: 300

db:
  driver: "mysql"
  dsn: "geodns:geodns_secret@tcp(mysql:3306)/geodns?charset=utf8mb4&parseTime=True&loc=Local"

geoip:
  enabled: true
  mmdb_path: "./geoipdb"
  reload_sec: 300
  use_ecs: true

update:
  enabled: true
  require_tsig: false
  tsig_secrets: {}

log:
  dns_verbose: true

performance:
  cache_size: 2048
  dns_timeout_sec: 5
  forwarder_timeout_sec: 3
