listen: "0.0.0.0:53"
forwarder: ""
enable_dnssec: false
# Local REST API token (for incoming requests to slave)
# api_token: "your-secure-token-here"  # Deprecated: use api_token_hash instead
api_token_hash: ""  # Generate with: ./namedot --gen-token yourToken
rest_listen: "0.0.0.0:8080"
auto_soa_on_missing: true
default_ttl: 300

db:
  driver: "sqlite"
  dsn: "file:namedot_slave.db?_foreign_keys=on"

geoip:
  enabled: true
  mmdb_path: "./geoipdb"
  reload_sec: 300
  use_ecs: true
  # download_urls:
  #   - "https://example.com/GeoLite2-Country.mmdb"
  #   - "https://example.com/GeoLite2-ASN.mmdb"
  # download_interval_sec: 86400  # 24 hours

update:
  enabled: false  # Auto-disabled in slave mode
  require_tsig: false
  tsig_secrets: {}

log:
  dns_verbose: true

performance:
  cache_size: 1024
  dns_timeout_sec: 2
  forwarder_timeout_sec: 2

admin:
  enabled: false  # Auto-disabled in slave mode
  username: admin
  password_hash: "$2a$10$0WB2kBhwpbU9.nmxVD2qs.4.1cz9vxrI8Vd58X7arA1rzp57B5zfW"

# Slave mode configuration
replication:
  mode: "slave"
  master_url: "http://master-server:8080"  # URL of the master server
  sync_interval_sec: 60  # Sync every 60 seconds
  api_token: "your-secure-token-here"  # Same token as on master
